name: apiverve_ifsclookup
description: IFSC Lookup is a simple tool for getting information on IFSC codes. It returns information on various IFSC codes.
version: 1.1.14
homepage: https://apiverve.com/marketplace/ifsclookup?utm_source=dart&utm_medium=homepage
repository: https://github.com/apiverve/ifsclookup-api/tree/main/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
